Traceback (most recent call last):
  File "3.py", line 37, in <module>
    with socketserver.TCPServer((host, port), MyTCPHandler) as server:
AttributeError: __exit__
'(no connection after 10 tries)
(testing 3)
(testing ../../../18SwDev/Code/2/Tests/1-in.json ../../../18SwDev/Code/2/Tests/1-out.json)
